export const courses = [
    {
        id: 1,
        name: 'CSS',
        description: 'In this lecture you will get introduced to CSS (Cascading Style Sheets) which you will use later to style and decorate your websites.<br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus magna velit, quis efficitur ante bibendum sollicitudin. Vestibulum sed convallis diam, eget sagittis ex. Etiam leo augue, consectetur sit amet dignissim ut, mollis quis mauris. Etiam vitae lorem mi. Proin mattis volutpat nulla ac aliquet. Proin nec tincidunt massa. Pellentesque nec commodo magna. Fusce mattis mauris non sem suscipit, vitae consequat leo ultrices. Aliquam id consequat tortor. Proin vel mauris feugiat, euismod nibh quis, ultrices risus. Suspendisse pellentesque lectus porttitor, facilisis elit nec, volutpat tortor.<br/>Sed hendrerit congue odio ac luctus. Nam consequat tortor lorem, ut hendrerit orci convallis ut. Etiam purus eros, tempus et tellus quis, venenatis porta nibh. Fusce congue mi ac metus vehicula, vel pharetra libero porta. Vivamus nunc nunc, ornare sit amet ante dictum, congue fermentum ante. Integer eros erat, consectetur eget erat quis, eleifend eleifend dolor. Quisque ipsum nisi, varius eu purus et, finibus euismod leo. Nunc eu porttitor massa. Aliquam sollicitudin sem quam, quis vestibulum justo gravida nec. Quisque gravida ipsum erat, eget ornare mauris dapibus id. Mauris consectetur augue quis nibh ullamcorper suscipit a laoreet lacus. Aliquam congue, tortor eget laoreet maximus, nisl risus suscipit lorem, quis cursus eros urna quis elit.',
        price: 50,
    },
    {
        id: 2,
        name: 'JavaScript',
        description: 'In this lecture, you will get introduced to JavaScript and the different powerful features it adds to your websites. You will create a nice webpage with an alert message showing up on page load.<br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus magna velit, quis efficitur ante bibendum sollicitudin. Vestibulum sed convallis diam, eget sagittis ex. Etiam leo augue, consectetur sit amet dignissim ut, mollis quis mauris. Etiam vitae lorem mi. Proin mattis volutpat nulla ac aliquet. Proin nec tincidunt massa. Pellentesque nec commodo magna. Fusce mattis mauris non sem suscipit, vitae consequat leo ultrices. Aliquam id consequat tortor. Proin vel mauris feugiat, euismod nibh quis, ultrices risus. Suspendisse pellentesque lectus porttitor, facilisis elit nec, volutpat tortor.<br/>Sed hendrerit congue odio ac luctus. Nam consequat tortor lorem, ut hendrerit orci convallis ut. Etiam purus eros, tempus et tellus quis, venenatis porta nibh. Fusce congue mi ac metus vehicula, vel pharetra libero porta. Vivamus nunc nunc, ornare sit amet ante dictum, congue fermentum ante. Integer eros erat, consectetur eget erat quis, eleifend eleifend dolor. Quisque ipsum nisi, varius eu purus et, finibus euismod leo. Nunc eu porttitor massa. Aliquam sollicitudin sem quam, quis vestibulum justo gravida nec. Quisque gravida ipsum erat, eget ornare mauris dapibus id. Mauris consectetur augue quis nibh ullamcorper suscipit a laoreet lacus. Aliquam congue, tortor eget laoreet maximus, nisl risus suscipit lorem, quis cursus eros urna quis elit.',
        price: 60,
    },
    {
        id: 3,
        name: 'jQuery',
        description: 'In this lecture, we will get introduced to the amazing features of JQuery which will make our JavaScript coding a lot easier. We will build a webpage and embed jQuery to it.<br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus magna velit, quis efficitur ante bibendum sollicitudin. Vestibulum sed convallis diam, eget sagittis ex. Etiam leo augue, consectetur sit amet dignissim ut, mollis quis mauris. Etiam vitae lorem mi. Proin mattis volutpat nulla ac aliquet. Proin nec tincidunt massa. Pellentesque nec commodo magna. Fusce mattis mauris non sem suscipit, vitae consequat leo ultrices. Aliquam id consequat tortor. Proin vel mauris feugiat, euismod nibh quis, ultrices risus. Suspendisse pellentesque lectus porttitor, facilisis elit nec, volutpat tortor.<br/>Sed hendrerit congue odio ac luctus. Nam consequat tortor lorem, ut hendrerit orci convallis ut. Etiam purus eros, tempus et tellus quis, venenatis porta nibh. Fusce congue mi ac metus vehicula, vel pharetra libero porta. Vivamus nunc nunc, ornare sit amet ante dictum, congue fermentum ante. Integer eros erat, consectetur eget erat quis, eleifend eleifend dolor. Quisque ipsum nisi, varius eu purus et, finibus euismod leo. Nunc eu porttitor massa. Aliquam sollicitudin sem quam, quis vestibulum justo gravida nec. Quisque gravida ipsum erat, eget ornare mauris dapibus id. Mauris consectetur augue quis nibh ullamcorper suscipit a laoreet lacus. Aliquam congue, tortor eget laoreet maximus, nisl risus suscipit lorem, quis cursus eros urna quis elit.',
        price: 55,
    },
    {
        id: 4,
        name: 'Angular',
        description: 'As Angular grows in popularity, new versions of the front-end framework are constantly being released. That’s why Udemy offers a wide range of courses covering every version of Angular available today.<br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus magna velit, quis efficitur ante bibendum sollicitudin. Vestibulum sed convallis diam, eget sagittis ex. Etiam leo augue, consectetur sit amet dignissim ut, mollis quis mauris. Etiam vitae lorem mi. Proin mattis volutpat nulla ac aliquet. Proin nec tincidunt massa. Pellentesque nec commodo magna. Fusce mattis mauris non sem suscipit, vitae consequat leo ultrices. Aliquam id consequat tortor. Proin vel mauris feugiat, euismod nibh quis, ultrices risus. Suspendisse pellentesque lectus porttitor, facilisis elit nec, volutpat tortor.<br/>Sed hendrerit congue odio ac luctus. Nam consequat tortor lorem, ut hendrerit orci convallis ut. Etiam purus eros, tempus et tellus quis, venenatis porta nibh. Fusce congue mi ac metus vehicula, vel pharetra libero porta. Vivamus nunc nunc, ornare sit amet ante dictum, congue fermentum ante. Integer eros erat, consectetur eget erat quis, eleifend eleifend dolor. Quisque ipsum nisi, varius eu purus et, finibus euismod leo. Nunc eu porttitor massa. Aliquam sollicitudin sem quam, quis vestibulum justo gravida nec. Quisque gravida ipsum erat, eget ornare mauris dapibus id. Mauris consectetur augue quis nibh ullamcorper suscipit a laoreet lacus. Aliquam congue, tortor eget laoreet maximus, nisl risus suscipit lorem, quis cursus eros urna quis elit.',
        price: 40,
    },
    {
        id: 5,
        name: 'ReactJS',
        description: 'Whether you’re interested in adding React to your existing dev skillset, or you want to develop full-stack web apps by using tools like NodeJS, Redux, and MongoDB in conjunction with React, Udemy has a comprehensive selection of courses to choose from.<br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus magna velit, quis efficitur ante bibendum sollicitudin. Vestibulum sed convallis diam, eget sagittis ex. Etiam leo augue, consectetur sit amet dignissim ut, mollis quis mauris. Etiam vitae lorem mi. Proin mattis volutpat nulla ac aliquet. Proin nec tincidunt massa. Pellentesque nec commodo magna. Fusce mattis mauris non sem suscipit, vitae consequat leo ultrices. Aliquam id consequat tortor. Proin vel mauris feugiat, euismod nibh quis, ultrices risus. Suspendisse pellentesque lectus porttitor, facilisis elit nec, volutpat tortor.<br/>Sed hendrerit congue odio ac luctus. Nam consequat tortor lorem, ut hendrerit orci convallis ut. Etiam purus eros, tempus et tellus quis, venenatis porta nibh. Fusce congue mi ac metus vehicula, vel pharetra libero porta. Vivamus nunc nunc, ornare sit amet ante dictum, congue fermentum ante. Integer eros erat, consectetur eget erat quis, eleifend eleifend dolor. Quisque ipsum nisi, varius eu purus et, finibus euismod leo. Nunc eu porttitor massa. Aliquam sollicitudin sem quam, quis vestibulum justo gravida nec. Quisque gravida ipsum erat, eget ornare mauris dapibus id. Mauris consectetur augue quis nibh ullamcorper suscipit a laoreet lacus. Aliquam congue, tortor eget laoreet maximus, nisl risus suscipit lorem, quis cursus eros urna quis elit.',
        price: 35,
    },
    {
        id: 6,
        name: 'VueJS',
        description: 'Whether you’re trying to build a full single-page application or merely add a bit of interactivity to your existing app, Vue.js has a spectrum of tools to help you get your job done, and Udemy has a course that can help you get up and running quickly.<br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus magna velit, quis efficitur ante bibendum sollicitudin. Vestibulum sed convallis diam, eget sagittis ex. Etiam leo augue, consectetur sit amet dignissim ut, mollis quis mauris. Etiam vitae lorem mi. Proin mattis volutpat nulla ac aliquet. Proin nec tincidunt massa. Pellentesque nec commodo magna. Fusce mattis mauris non sem suscipit, vitae consequat leo ultrices. Aliquam id consequat tortor. Proin vel mauris feugiat, euismod nibh quis, ultrices risus. Suspendisse pellentesque lectus porttitor, facilisis elit nec, volutpat tortor.<br/>Sed hendrerit congue odio ac luctus. Nam consequat tortor lorem, ut hendrerit orci convallis ut. Etiam purus eros, tempus et tellus quis, venenatis porta nibh. Fusce congue mi ac metus vehicula, vel pharetra libero porta. Vivamus nunc nunc, ornare sit amet ante dictum, congue fermentum ante. Integer eros erat, consectetur eget erat quis, eleifend eleifend dolor. Quisque ipsum nisi, varius eu purus et, finibus euismod leo. Nunc eu porttitor massa. Aliquam sollicitudin sem quam, quis vestibulum justo gravida nec. Quisque gravida ipsum erat, eget ornare mauris dapibus id. Mauris consectetur augue quis nibh ullamcorper suscipit a laoreet lacus. Aliquam congue, tortor eget laoreet maximus, nisl risus suscipit lorem, quis cursus eros urna quis elit.',
        price: 30,
    }
]